const moviesList = [
  'Jurassic Park',
  'The Lost World: Jurassic Park',
  'The Kissing Booth 2',
  'Transcendence',
  'Train to Busan',
  'The Lord of the Rings: The Return of the King',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Lord of the Rings: The Two Towers',
  '12 Years a Slave',
  'The Core',
  'The Day After Tomorrow',
  'The Big Sick',
  'The Theory of Everything',
  'Casablanca',
  'Cast Away',
  'The Princess Bride',
  'Real Steel',
  'The Platform',
  'The Departed',
  'Demolition',
  'Die Hard',
  'Die Hard 2',
  'Die Hard: With a Vengeance',
  'Live Free or Die Hard',
  'Gone Girl',
  'Panic Room',
  'Catch Me If You Can',
  'The Interview',
  'Slumdog Millionaire',
  'Frozen',
  'Frozen II',
  'The Martian',
  'Palm Springs',
  'The Body',
  'The Curious Case of Benjamin Button',
  'The Karate Kid',
  'Hawking',
  'Alien',
  'Contact',
  'The Hunger Games: Catching Fire',
  'The Hunger Games: Mockingjay - Part 1',
  'Se7en',
  'In Time',
  'Weathering with You',
  'Night at the Museum',
  'The Lunchbox',
  'Saving Private Ryan',
  'Patch Adams',
  'The Half of It',
  '12 Strong',
  'Confessions',
  'Harry Potter and the Prisoner of Azkaban',
  'Star Trek',
  'Stardust',
  'The Boy in the Striped Pyjamas',
  'Just Mercy',
  'The Godfather',
  'The Big Short',
  'The Way Back',
  'Kannum Kannum Kollaiyadithaal',
  'Memories of Murder',
  'Maayavan',
  'Little Women',
  'Oh My Kadavule',
  'Star Wars: The Rise of Skywalker',
  '1917',
  'National Treasure',
  'Travelling Salesman',
  'Casino Royale',
  'Snowpiercer',
  'Gladiator',
  'Waves',
  '21 Bridges',
  'Knives Out',
  'A Beautiful Day in the Neighborhood',
  'Jojo Rabbit',
  'A Rainy Day in New York',
  'Burning',
  'Liberal Arts',
  'Columbus',
  'Chhichhore',
  'Sillu Karupatti',
  'Top Gun',
  'Serendipity',
  'V for Vendetta',
  'What If',
  'Dunkirk',
  'Crazy Rich Asians',
  'Ford v Ferrari',
  'Darbar',
  'Donnie Darko',
  'Joker',
  'One Day',
  'Kaithi',
  'Marriage Story',
  'Ad Astra',
  'Chungking Express',
  'The Report',
  'Zombieland: Double Tap',
  'Paterson',
  'Parasite',
  'The Irishman',
  'No Strings Attached',
  'Asuran',
  'The Current War',
  'The Farewell',
  'Once Upon a Time… in Hollywood',
  'Good Boys',
  'Bigil',
  'Us',
  'Scott Pilgrim vs.the World',
  'Whiplash',
  'The Lion King',
  'Dallas Buyers Club',
  'El Camino: A Breaking Bad Movie',
  'The Art of Self - Defense',
  'Boyhood',
  'Sicario',
  'Coherence',
  'Crazy, Stupid, Love.',
  '  Booksmart',
  'Armageddon',
  'Spider - Man: Far from Home',
  'The Keeper',
  'The Edge of Seventeen',
  'The Amazing Spider - Man 2',
  'Captain America: The Winter Soldier',
  'Superbad',
  'Tolkien',
  'When Harry Met Sally...',
  'Pride & Prejudice',
  'The Amazing Spider - Man',
  'Zombieland',
  'You\'ve Got Mail',
  'Aladdin',
  'WALL·E',
  'Captain America: The First Avenger',
  'Natpe Thunai',
  'Drive',
  'Kanaa',
  'Midnight in Paris',
  'Gully Boy',
  'Then Came You',
  'Avengers: Endgame',
  'Thadam',
  'Reservoir Dogs',
  'Friends with Benefits',
  'Okja',
  'Escape Room',
  'Shazam!',
  'The Girl Next Door',
  '2.0',
  'Django Unchained',
  'How to Train Your Dragon: The Hidden World',
  'Kill Bill: Vol. 1',
  'Kill Bill: Vol. 2',
  'My Name Is Khan',
  'Taxi Driver',
  'Bumblebee',
  'Inglourious Basterds',
  'Southpaw',
  'If Beale Street Could Talk',
  'Triple Frontier',
  'Spider - Man: Into the Spider - Verse',
  'Project Gutenberg',
  'The Silence of the Lambs',
  'Instant Family',
  'Sarvam Thaala Mayam',
  'Viswasam',
  'National Geographic: Journey to the Edge of the Universe',
  'Your Name.',
  'On Your Wedding Day',
  'Mortal Engines',
  'K.G.F: Chapter 1',
  'Shoplifters',
  'Velvet Buzzsaw',
  'Take the Ball, Pass the Ball',
  'Risky Business',
  'Adanga Maru',
  'Thuppakki Munai',
  'Maari 2',
  'Bohemian Rhapsody',
  'Me and Earl and the Dying Girl',
  'Andhadhun',
  'Silukkuvarupatti Singam',
  'The Girl in the Spider\'s Web',
  'Pariyerum Perumal',
  'Johnny English Strikes Again',
  'A Star Is Born',
  'Beautiful Boy',
  'Petta',
  'Loophole',
  'Tomorrow I Will Date With Yesterday\'s You',
  'Rust Creek',
  'The Shawshank Redemption',
  'The Guilty',
  'Bird Box',
  'Thor',
  'Thor: The Dark World',
  'Citizen Kane',
  'First Man',
  'The Net',
  '12 Angry Men',
  '27 Dresses',
  '8 Mile',
  '96',
  'X + Y',
  'A Dog\'s Purpose',
  'A Few Good Men',
  'A Walk to Remember',
  'About Time',
  'Adrift',
  'Alex Strangelove',
  'Almost Friends',
  'American Made',
  'An Interview with God',
  'Annihilation',
  'Ant - Man and the Wasp',
  'Apollo 13',
  'Aquaman',
  'Avengers: Infinity War',
  'Away You Go',
  'Back to the Future',
  'Back to the Future Part III',
  'Back to the Future Part II',
  'Bad Genius',
  'Before Sunrise',
  'Before Sunset',
  'Before Midnight',
  'Black Mirror: Bandersnatch',
  'Black Panther',
  'Brain on Fire',
  'Breathe',
  'Brothers',
  'Call Me by Your Name',
  'Chekka Chivantha Vaanam',
  'Children of Men',
  'Coco',
  'Comet',
  'CIA: Comrade In America',
  'Darkest Hour',
  'Deadpool 2',
  'Den of Thieves',
  'Destination Wedding',
  'Eighth Grade',
  'Enemy at the Gates',
  'Escape Plan 2: Hades',
  'Fantastic Beasts: The Crimes of Grindelwald',
  'Game Night',
  'Google and the World Brain',
  'Happy Death Day',
  'Her',
  'How to Talk to Girls at Parties',
  'Imaikkaa Nodigal',
  'Raiders of the Lost Ark',
  'Indiana Jones and the Temple of Doom',
  'Indiana Jones and the Last Crusade',
  'Indiana Jones and the Kingdom of the Crystal Skull',
  'Irumbu Thirai',
  'Jonathan',
  'Jumanji: Welcome to the Jungle',
  'Junga',
  'Juno',
  'Kolamavu Kokila',
  'Lady Bird',
  'Little Miss Sunshine',
  'Locke',
  'Love Actually',
  'Love & Other Drugs',
  'Love, Rosie',
  'Love, Simon',
  'Maze',
  'Mean Girls',
  'Million Dollar Baby',
  'Moneyball',
  'Murder on the Orient Express',
  'My Best Friend\'s Wedding',
  'Nerve',
  'No Country for Old Men',
  'Not Cinderella\'s Type',
  'October Sky',
  'Patriots Day',
  'Pulp Fiction',
  'Puzzle',
  'Rampage',
  'Ratsasan',
  'Ready Player One',
  'Saamy²',
  'Sarkar',
  'Schindler\'s List',
  'Searching',
  'Serenity',
  'Set It Up',
  'She\'s the Man',
  'Sierra Burgess Is a Loser',
  'Skyscraper',
  'Speed',
  'Stuck in Love',
  'Tag',
  'Tamizh Padam 2',
  'The Bank Job',
  'The Breakfast Club',
  'The Commuter',
  'The Darkest Minds',
  'The First Purge',
  'The First Time',
  'The Greatest Showman',
  'The Hunt for Red October',
  'The Invisible Guest',
  'The King\'s Speech',
  'The Kissing Booth',
  'The Last Samurai',
  'The Meg',
  'The Notebook',
  'The Post',
  'The Proposal',
  'The Quake',
  'The Shape of Water',
  'The Spectacular Now',
  'The Terminal',
  'The Wave',
  'Thor: Ragnarok',
  'Three Billboards Outside Ebbing, Missouri',
  'Tik Tik Tik',
  'Tinker\'',
  'Titanic',
  'To All the Boys I\'ve Loved Before',
  'To the Bone',
  'Tomb Raider',
  'Transition',
  'U Turn',
  'Vada Chennai',
  'Velaikkaran',
  'When We First Met',
  'Wild Tales',
  'Wind River',
  'Wonder',
  'Wreck - It Ralph',
  'Hacksaw Ridge',
  'Neerja',
  'Mission: Impossible',
  'Captain Phillips',
  'Portrait of a Lady on Fire',
];

export {
  // eslint-disable-next-line import/prefer-default-export
  moviesList,
};
